import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
<style jsx global>{`
  html {
    color-scheme: light;
  }
  body {
    color: #111827; /* Tailwind gray-900 */
    background-color: #f5f5f5;
  }
`}</style>

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
